### ISSUE TITLE
Koshei the Deathless Quest

### ISSUE THREAD

**Issue by LoungeLizard91** [tibiamaps/tibia-map-data#109]
Hi.
I was following the instructions for the Koshei the Deathless Quest on Tibia wiki and noticed that the pathing to "a sweaty cyclops" in Ab'dendriel was a little off. 
The instructions in writing is correct but the hole you need to go down in the weatfield is inside a house on the mapper. The map  down in the hole is off as well.

This is not a big deal or anything, but thought I should mention it.

**Comment by LeeKunTibia** [comment]
Hi @LoungeLizard91.

I have fixed that on TibiaWiki, thanks for the information.

By the way, since this was just a problem with the link it's only related to TibiaWiki, such issues can be reported on TibiaWiki's talk pages or our [Discord Server](https://tibia.fandom.com/wiki/TibiaWiki:Discord), since they aren't really related to the map data or TibiaMaps. :) 

Of course, you can always edit pages and fix these kinds of problems yourself, if you want to.
