### ISSUE TITLE
Little map discovery

### ISSUE THREAD

**Issue by Bosst-Williams** [tibiamaps/tibia-map-data#130]
Hello,

This is Bosst from Tibiasecrets.com. I would like to contribute to your project with our little discovery in Yalahar's Alchemist quarter.
I'm talking about the 2 "holes" in this room: X: 32718 Y: 31183 Z: 9. You can go down these holes to level -3 using levitate and unlock a small bit of map which is missing on your site.
I'm attaching the files.

![Minimap_Color_32512_30976_10](https://user-images.githubusercontent.com/79009140/107850741-f4263000-6e04-11eb-84e7-3dccf5bde6b0.png)
![Minimap_WaypointCost_32512_30976_10](https://user-images.githubusercontent.com/79009140/107850742-f4bec680-6e04-11eb-92e6-f531ccc7ba08.png)

**Comment by mathiasbynens** [comment]
Hey @Bosst-Williams, nice to see you here! As you know I'm a big fan of your work :)

Thanks for discovering this area and for sharing those maps. Would you mind putting the PNGs into a ZIP file, and then uploading the ZIP here? I ask because GitHub compresses PNG files upon upload which has reduced accuracy of contributed map files in the past.

The coordinates you point to are here: https://tibiamaps.io/map#32718,31183,9:2 I'm guessing you meant these holes in particular: https://tibiamaps.io/map#32715,31170,9:2 and https://tibiamaps.io/map#32710,31170,9:2

**Comment by Bosst-Williams** [comment]
Hey, thank you for the kind words :)
I've just found out that holes to the left (https://tibiamaps.io/map#32691,31178,9:2) are inevitable too! You will find the updated map files in the attached ZIP.

[alchemist maps.zip](https://github.com/tibiamaps/tibia-map-data/files/5975725/alchemist.maps.zip)
