### ISSUE TITLE
Children of the Revolution: explore second floor during Strike mission

### ISSUE THREAD

**Issue by Sixish** [tibiamaps/tibia-map-data#15]
You can levitate up on one of the buildings during [the Strike mission of Children of the Revolution](http://tibia.wikia.com/wiki/Children_of_the_Revolution_Quest/Spoiler#Weekly_Task:_Zze_Art_of_War).

This one, I believe: https://tibiamaps.io/map#33277,31114,7:2

![cotr5-levitate-room](https://cloud.githubusercontent.com/assets/2226286/13905101/cc0668a8-eef0-11e5-8c32-1b9c41011f7a.png)

**Comment by mathiasbynens** [comment]
@Sixish Do you happen to have this area explored? If so, could you upload `12912106.map` and `13012106.map` here please?

**Comment by Sixish** [comment]
@mathiasbynens nah I took this screenshot a long while back.

**Comment by LeeKunTibia** [comment]
Shouldn't this be closed? I think it should, since:

1. The roofs here shouldn't be accessible, it they were, it was a bug, otherwise the mission/task would be pointless. Furthermore, I just went there and couldn't levitate anywhere on that building, so I guess it was fixed. 

2. Regardless of the above, there are some roofs explored in the current maps. They were explored some time this year because the maps I downloaded in January don't have them. 

So not only I think it would be impossible to solve this, it looks like it was already solved.
