### ISSUE TITLE
Move Thais portal markers

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#167]
Codina would like them to be 1 sqm to the south, so you don't enter the portal and die when clicking them.

**Comment by LeeKunTibia** [comment]
What about every other portal, though?

**Comment by rmobis** [comment]
I would love to see a single marker in the center of Halls of Hope instead of one for each portal. Apart from the _entering in the portal and dying_ issue, it's not like having 7 icons crammed in 14 pixels makes life easier when picking a specific one. And once you're there, it's pretty easy to see which one is which.

If that's an agreement, I could open a PR later. Let me know.

**Comment by mathiasbynens** [comment]
Yeah, I agree. Let's mark a single one.

**Comment by mathiasbynens** [comment]
I just removed the portal-specific markers, since we already have a marker there: f83ab9c393a717b24d60e6ae2f2b06367bc1eb11
