### ISSUE TITLE
Color pngs are missing but WaypointCost present

### ISSUE THREAD

**Issue by Diego1149** [tibiamaps/tibia-map-data#187]
I'm doing a tool to help understand given the speed and location of your character how many seconds it will take it to reach to a destination; therefore I need both the Color and WaypointCost; however, there are some Color images that are missing, whereas the WaypointCosts are present:

Minimap_Color_32768_32768_0
Minimap_Color_33280_31744_1
Minimap_Color_33280_32768_5
Minimap_Color_33280_32768_6
Minimap_Color_33536_32000_0
Minimap_Color_33536_32000_1
Minimap_Color_33536_32000_2

Also as an additional note, I see that given that the format used is 256x256 pixels and there are 8 different X and Y coordinates, there should be 1024 images (8*8*16), but I only see 989 WaypointCost and 982 Color.

My guess is that the missing 35 WaypointCost are innaccessible and therefore not explored, but just wanted to see if this is known.

**Comment by LeeKunTibia** [comment]
When you explore an area and there are empty fields around you, such as the case of "air" around buildings/mountains above ground, there will be nothing to register on the Minimap Color files, since there aren't objects there. On the other hand, empty fields are registered on waypoint files as yellow pixels, which means they are unwalkable tiles. Because of that, the waypoint files of these locations usually have a yellow border around the areas you can walk, which lead to more data in the waypoint files than in the color files.
![Color x Waypoint Maps](https://user-images.githubusercontent.com/31053487/152048103-495244b4-6566-4cd2-b9ec-1a654554b716.gif)


When this happens on the edges of file limits and there's nothing else in that section, you can have this situation of only the waypoint file existing. If you need to, you can simply consider or create the missing color files as a completely black square. 

Regarding the number of files, as you suggested that's because these areas haven't been explored. I'm not familiar with the transformation scripts but I suppose that it doesn't generate files if they won't contain any data.
