### ISSUE TITLE
Missing Ghostship ground floor

### ISSUE THREAD

**Issue by mathiasbynens** [tibiamaps/tibia-map-data#94]
This was in the Odyssey data: https://tibiamaps.io/map#33326,32173,7:3

**Comment by mathiasbynens** [comment]
From Hunter:

> the `File:Minimap_Floor_7.png` versions from 14 September 2017 and [28 November 2017](https://vignette.wikia.nocookie.net/tibia/images/6/64/Minimap_Floor_7.png/revision/latest?cb=20200619043309&path-prefix=en) contain the ghostship's ground floor completely explored, you might want to check TibiaMap's ground floor files from that time :wink:

**Comment by Hunter-of-Dragoes** [comment]
Links are: [14 September 2017](https://vignette.wikia.nocookie.net/tibia/images/6/64/Minimap_Floor_7.png/revision/20171128141904?path-prefix=en) and [28 November 2017](https://vignette.wikia.nocookie.net/tibia/images/6/64/Minimap_Floor_7.png/revision/20181121020726?path-prefix=en).
It would be nice to check when they got removed from TibiaMaps and search for more possibly removed areas.

**Comment by LeeKunTibia** [comment]
The data was removed on ad28428

On this update there were some changes to Darashia and the files used to update the map did not have the ground floor of the ghost ship. 

I manually edited the minimap file to re-add the ship. As a bonus I also updated the Cake Island because it was a mix of eaten/not eaten. 

[Minimap_Color_33280_32000_7.zip](https://github.com/tibiamaps/tibia-map-data/files/5901714/Minimap_Color_33280_32000_7.zip)
