### ISSUE TITLE
The Doors

### ISSUE THREAD

**Issue by TibiaBaker** [tibiamaps/tibia-map-data#99]
I have just returned to Tibia after many years of absence, so maybe this won't be news to you, but I've read TibiaMaps and I didn't find mentions of it, so I thought I'll share anyway.

The doors and fences act funny. When you are in the game and open or close the door or fence, the minimap changes accordingly and it gets saved next time you close Tibia. It is reflected in the `Minimap_Color_*.png` and `Minimap_WaypointCost_*.png`. 

Because of this, the data in this repo are... inaccurate. Well, I'm not really sure if I can say they are inaccurate, but they naturally reflect only on of the possible states.

**Comment by mathiasbynens** [comment]
Indeed, the pathfinding data is constantly updated as you walk through the game, depending on whether or not doors are open vs. closed. We generally try to map things with doors open where it makes sense for them to be open (to enable optimal mapclicking), but we indeed don't always manage to. It's tricky to maintain the open doors everywhere since we often have to re-explore existing areas once CipSoft updates them.
